# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'University of Cambridge: Data Science Autumn School'
baseurl:          https://cambiotraining.github.io/DataScienceSchool/


paginate:         5

# Custom vars
version:          2.1.0
